environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

branches:
  # whitelist
  only:
    - master

cache:
  - "C:\\wheels"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "pip -q install wheel"
  # Create c:/wheels if it does not exist.
  - ps: If ( -not (Test-Path C:\\wheels) )  { mkdir C:\\wheels }
  - ECHO "Cached wheels:"
  - ps: "ls \"C:\\wheels\""
  - "pip -q wheel --use-wheel --wheel-dir C:\\wheels --find-links C:\\wheels -r test-requirements.txt"
  - "pip -q wheel --use-wheel --wheel-dir C:\\wheels --find-links C:\\wheels -r requirements.txt"
  - "pip -q wheel --use-wheel --wheel-dir C:\\wheels --find-links C:\\wheels -r gui-requirements.txt"
  - "pip -q install --find-links=C:\\wheels -r test-requirements.txt"
  - "pip -q install --find-links=C:\\wheels -r requirements.txt"
  - "pip -q install --find-links=C:\\wheels -r gui-requirements.txt"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "python setup.py install"
  - "python -m pytest"
